export const browserCoreExamples = [
  "selfer browser status",
  "selfer browser start",
  "selfer browser stop",
  "selfer browser tabs",
  "selfer browser open https://example.com",
  "selfer browser focus abcd1234",
  "selfer browser close abcd1234",
  "selfer browser screenshot",
  "selfer browser screenshot --full-page",
  "selfer browser screenshot --ref 12",
  "selfer browser snapshot",
  "selfer browser snapshot --format aria --limit 200",
  "selfer browser snapshot --efficient",
  "selfer browser snapshot --labels",
];

export const browserActionExamples = [
  "selfer browser navigate https://example.com",
  "selfer browser resize 1280 720",
  "selfer browser click 12 --double",
  'selfer browser type 23 "hello" --submit',
  "selfer browser press Enter",
  "selfer browser hover 44",
  "selfer browser drag 10 11",
  "selfer browser select 9 OptionA OptionB",
  "selfer browser upload /tmp/selfer/uploads/file.pdf",
  'selfer browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "selfer browser dialog --accept",
  'selfer browser wait --text "Done"',
  "selfer browser evaluate --fn '(el) => el.textContent' --ref 7",
  "selfer browser console --level error",
  "selfer browser pdf",
];
